### ISSUE TITLE
[Reproducing results] Cannot run the codebase / detector pretraining

### ISSUE THREAD

**Issue by j-rausch** [ubc-vision/segmentation-sg#4]
Thanks for this great project and the open-source contribution!

I'm trying to reproduce your results at the moment and would like to get started with training the baseline and segmentation-grounded methods for MOTIF using ResNeXt.
As a first step, I'm trying to run your first code snippet for detector pretraining with following arguments:

```
python pretrain_object_detector_withcoco.py --config-file ./configs/pretrain_object_detector_coco.yaml --num-gpus 4 --resume DATASETS.VISUAL_GENOME.IMAGES ./datasets/vg/VG_100K/ DATASETS.VISUAL_GENOME.MAPPING_DICTIONARY ./datasets/vg/VG-SGG-dicts-with-attri.json DATASETS.VISUAL_GENOME.IMAGE_DATA ./datasets/vg//image_data.json DATASETS.VISUAL_GENOME.VG_ATTRIBUTE_H5 ./datasets/vg/VG-SGG-with-attri.h5 DATASETS.MSCOCO.ANNOTATIONS ./datasets/coco/annotations/ DATASETS.MSCOCO.DATAROOT ./datasets/mscoco/ OUTPUT_DIR ./data/checkpoints/debug/
```

I've tried running the code with detectron2==0.3 and upwards.
At the moment I'm running into some issues when trying to run the detector pretraining:

I adapted the foldername to `segmentationsg` as recommended in the instructions.
Some imports fail when trying to run `pretrain_object_detector_withcoco.py`, e.g. `from SceneGraph.engine import ObjectDetectorTrainerWithCoco` (https://github.com/ubc-vision/segmentation-sg/blob/main/scripts/pretrain_object_detector_withcoco.py#L16
) likely because the project folder was differently named originally.

There are some hardcoded paths such as in https://github.com/ubc-vision/segmentation-sg/blob/main/data/datasets/visual_genome.py#L34

After adapting these imports and paths, I'm running into following error:

```
...
  File "/pathto/segmentationsg/engine/trainer.py", line 154, in __init__
    super(ObjectDetectorTrainerWithCoco, self).__init__(cfg)
  File "/pathtoenv/site-packages/detectron2/engine/defaults.py", line 376, in __init__
    model = self.build_model(cfg)
  File "/pathtoenv/site-packages/detectron2/engine/defaults.py", line 505, in build_model
    model = build_model(cfg)
  File "/pathtoenv/site-packages/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/pathtoenv/site-packages/fvcore/common/registry.py", line 71, in get
    raise KeyError(
KeyError: "No object named 'GeneralizedRCNNWithCOCO' found in 'META_ARCH' registry!"
```

It seems that `.modeling.meta_arch.rcnn` is not run/imported before `trainer.py` is run. I'm currently working around this by importing it at the beginning of `trainer.py`.

After these adjustments I can run the code up to this point:

```  
File "/pathto/segmentationsg/engine/trainer.py", line 295, in run_step
    data = next(self._data_loader_iter)
AttributeError: 'ObjectDetectorTrainerWithCoco' object has no attribute '_data_loader_iter'
```

I can fix this by adjusting the code to:
```data = next(self._trainer._data_loader_iter)```
instead of
```data = next(self._data_loader_iter)```

After these changes, I'm running into the next issue. I'd address this in a separate issue, to not clutter this issue too much.

I'm wondering if you could help me out with instructions or code examples on how to successfully run and reproduce the experiments in your paper. Perhaps there is a more recent version for the (pre)training scripts or I'd need to make any other adjustments?

**Comment by siddheshk** [comment]
Hi, this might be due to the version of detectron2 you have installed. I would recommend using 0.2.1 or earlier. You can see the _data_loader_iter present in these versions here: https://github.com/facebookresearch/detectron2/blob/v0.2.1/detectron2/engine/train_loop.py#L208

The failures you are seeing are probably related to this. I will update the version info in the README.

**Comment by j-rausch** [comment]
Hey, thanks for your reply! I was using detectron 0.3 or higher, because of the info from [this issue](https://github.com/ubc-vision/segmentation-sg/issues/3). I'll try out detectron 0.2.1 as well.

I think that some other parts, e.g. `from SceneGraph.engine import ObjectDetectorTrainerWithCoco`, without there being a `SceneGraph` library installed or existing folder name, would still cause exceptions.

Could you possibly check if the codebase in this repository can be executed on your setup?

**Comment by siddheshk** [comment]
The code works on my machine. But I will take a look soon and check if the code can be executed on a fresh environment.

**Comment by siddheshk** [comment]
Hi, 
I've made some edits and pushed a new version of the code. I forgot to rename the imports in the `pretrain_object_detector_withcoco.py` file. Sorry about that. Everything should now work if you rename the folder to `segmentationsg`. 
Regarding the issue with other imports, it turns out the detectron2 release version is different from the version we used to build the codebase. We built it from the github repo itself and therefore there are some discrepancies with `_data_loader_iter` not being found. But I've fixed that, and now the code works on `detectron2 v0.3` with `pytorch 1.6` and `cuda 10.2`. You can find a pip version of this release here : https://github.com/facebookresearch/detectron2/releases
In case you don't want to pretrain things yourself, you can find the pretrained weights here: https://drive.google.com/drive/folders/1YZ3ipSi_ao_Xl9UsMBbmro7sp2mi8bqr

**Comment by j-rausch** [comment]
Thanks a lot, your commit seems to resolve the issues with detectron2 v0.3 and pytorch 1.7!
